apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: s4snxa0je-go 
  janus-idp.io/tekton: s4snxa0je-go
  backstage.io/kubernetes-id: s4snxa0je-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: s4snxa0je-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml